### ISSUE TITLE
[0.13.0-alpha] ALB panic

### ISSUE THREAD

**Issue by karlesnine** [ivx/yet-another-cloudwatch-exporter#56]
Hello

With version 0.13.0-alpha for ALB we have this error message and the probing fail 

```
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: 2019/03/27 16:49:34 http: panic serving 172.21.32.190:42236: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "aws_alb_request_count_sum", help: "Help is not implemented yet.", constLabels: {dimension_LoadBalancer="app/awseb-AWSEB-W3MG4A5Z5SW0/7978fae386c94fa3",name="arn:aws:elasticloadbalancing:eu-west-1:687944316825:loadbalancer/app/awseb-AWSEB-W3MG4A5Z5SW0/7978fae386c94fa3",tag_Name="vc-prod-rum",tag_Project="rum"}, variableLabels: []}
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: goroutine 1208 [running]:
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: net/http.(*conn).serve.func1(0xc4209f2140)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:1726 +0xd0
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: panic(0x8f4d40, 0xc420a36a60)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/runtime/panic.go:502 +0x229
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: yace/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc420a640a0, 0xc420667cd0, 0x1, 0x1)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /go/src/yace/vendor/github.com/prometheus/client_golang/prometheus/registry.go:391 +0x9e
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: main.metricsHandler(0xa340e0, 0xc42044a540, 0xc420176400)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /go/src/yace/main.go:50 +0x2e2
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: net/http.HandlerFunc.ServeHTTP(0x9b3580, 0xa340e0, 0xc42044a540, 0xc420176400)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:1947 +0x44
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: net/http.(*ServeMux).ServeHTTP(0xcaec60, 0xa340e0, 0xc42044a540, 0xc420176400)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:2340 +0x130
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: net/http.serverHandler.ServeHTTP(0xc420173040, 0xa340e0, 0xc42044a540, 0xc420176400)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:2697 +0xbc
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: net/http.(*conn).serve(0xc4209f2140, 0xa35ae0, 0xc420238040)
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:1830 +0x651
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]: created by net/http.(*Server).Serve
Mar 27 16:49:34 vc-prod-rum-exporter-01 yace_exporter[29952]:         /usr/local/go/src/net/http/server.go:2798 +0x27b
```

Our setting for ALB is 

```
discovery:
  exportedTagsOnMetrics:
    vpn:
      - Project
      - Name
    elb:
      - Project
      - Name
    rds:
      - Project
      - Name
    ec:
     - Project
     - Name
    lambda:
     - Project
     - Name
    alb:
     - Project
     - Name

  jobs:
  - region: {{ ec2_region }}
    type: "vpn"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: TunnelState
        statistics:
        - 'Maximum'
        period: 60
        length: 300
      - name: TunnelDataOut
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: TunnelDataIn
        statistics:
        - 'Sum'
        period: 60
        length: 300
  - region: {{ ec2_region }}
    type: "lambda"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: Throttles
        statistics:
        - 'Average'
        period: 60
        length: 300
      - name: Invocations
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: Errors
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: Duration
        statistics:
        - 'Average'
        period: 60
        length: 300
      - name: Duration
        statistics:
        - 'Minimum'
        period: 60
        length: 300
      - name: Duration
        statistics:
        - 'Maximum'
        period: 60
        length: 300
  - region: {{ ec2_region }}
    type: "ec"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: NewConnections
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: GetTypeCmds
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: SetTypeCmds
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: CacheMisses
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: CacheHits
        statistics:
        - 'Sum'
        period: 60
        length: 300
  - region: {{ ec2_region }}
    type: "rds"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: DatabaseConnections
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: ReadIOPS
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: WriteIOPS
        statistics:
        - 'Sum'
        period: 60
        length: 300
  - region: {{ ec2_region }}
    type: "elb"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: RequestCount
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: HealthyHostCount
        statistics:
        - 'Minimum'
        period: 60
        length: 300
      - name: UnHealthyHostCount
        statistics:
        - 'Maximum'
        period: 60
        length: 300
      - name: HTTPCode_Backend_2XX
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: HTTPCode_Backend_5XX
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: HTTPCode_Backend_4XX
        statistics:
        - 'Sum'
        period: 60
        length: 300
  - region: {{ ec2_region }}
    type: "alb"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: RequestCount
        statistics:
        - 'Sum'
        period: 600
        length: 600
      - name: HealthyHostCount
        statistics:
        - 'Minimum'
        period: 600
        length: 600
      - name: UnHealthyHostCount
        statistics:
        - 'Maximum'
        period: 600
        length: 600
      - name: HTTPCode_Target_2XX
        statistics:
        - 'Sum'
        period: 600
        length: 600
      - name: HTTPCode_Target_5XX
        statistics:
        - 'Sum'
        period: 600
        length: 600
      - name: HTTPCode_Target_4XX
        statistics:
        - 'Sum'
        period: 60
        length: 60

```

It's more stable when we use 
```
        period: 60
        length: 60

```
But, in this case, we have data gaps

**Comment by tsupertramp** [comment]
Okay i can see this happening and can make it crash on purpose.

You can quick fix this by setting different tags on your target group vs your alb and then use two jobs. One for Target Group metrics and one for ALB metrics.

I am unsure who i will solve this to be still easy to use.

Currently thinking that ALB requires a different scraping setup as it is not enough to check the ALB metrics. You need the TargetGroup Metrics as well. Maybe use the ALB api to first gather the services to monitor.

Wanted to spent an hour on this and spent two. I will work something out and inform you.

**Comment by karlesnine** [comment]
Use different tag on my target group vs alb is not possible. The Project tag is use for billing to and many other stuff. If we do that's we will have two different project to manage for the same use

**Comment by tsupertramp** [comment]
Thanks for mentioning this use case.

I will try to migrate this as experiment to 'real' API calls to discover resources instead of service discovery via tags.

**Comment by tsupertramp** [comment]
Found a fix for this. Will be released today.

**Comment by tsupertramp** [comment]
Solved and released :) - Sorry for the long delay.
