### ISSUE TITLE
[0.13.0-alpha] IAM Policies

### ISSUE THREAD

**Issue by karlesnine** [ivx/yet-another-cloudwatch-exporter#57]
Since 0.13.0-alpha the IAM policy needed is this one

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "tag:GetResources",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics"
            ],
            "Resource": "*"
        }
    ]
}
```

If not you have this error message

```
panic: AccessDenied: User: arn:aws:sts::687944316825:assumed-role/vc-prod-setting-role/i-0beed10f8be074647 is not authorized to perform: cloudwatch:ListMetrics
	status code: 403, request id: 5b0b4c8f-513e-11e9-9035-1bb5a5f5a512


goroutine 161 [running]:
main.getResourceValue(0x994f55, 0xc, 0xc4201ae448, 0x1, 0x1, 0xc4201eaf40, 0xa3d040, 0xc42000c358, 0x8d00e0)
	/go/src/yace/aws_cloudwatch.go:177 +0xfa
main.queryAvailableDimensions(0xc420067924, 0x36, 0xc4201eaf40, 0xa3d040, 0xc42000c358, 0x14, 0xc42006790d, 0x9)
	/go/src/yace/aws_cloudwatch.go:193 +0x453
main.getDimensions(0xc4200692d0, 0xc4201ea7c0, 0xa3d040, 0xc42000c358, 0x47f378, 0xc4201bcaf8, 0x1)
	/go/src/yace/aws_cloudwatch.go:218 +0x110c
main.scrapeDiscoveryJob.func1(0xc420229a10, 0xa3d040, 0xc42000c358, 0xc420023d00, 0x9, 0xc420023cfc, 0x3, 0x0, 0x0, 0xc4201ec640, ...)
	/go/src/yace/abstract.go:120 +0x66
created by main.scrapeDiscoveryJob
	/go/src/yace/abstract.go:119 +0x247
```

**Comment by tsupertramp** [comment]
Sorry for the bad user experience during upgrade. That was not intended. Thanks for clarification what was missing through debug log.

Updated docs and CHANGELOG in a branch commit. This will get merged with next version.
