### ISSUE TITLE
Problem: AddCloudwatchTimestamp null pointer

### ISSUE THREAD

**Issue by wutianchen** [ivx/yet-another-cloudwatch-exporter#67]
I got the following error

```
2019/05/08 10:23:49 http: panic serving 192.168.64.14:60592: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc0001c00a0)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xafe9e0, 0x124f330)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
main.migrateCloudwatchToPrometheus(0xc0005b4000, 0x8a5, 0xa00, 0x12, 0xc0001b4340, 0x3)
        /opt/aws_cloudwatch.go:435 +0x1203
main.metricsHandler(0xd34ca0, 0xc000266000, 0xc0001bea00)
        /opt/main.go:59 +0xa9
net/http.HandlerFunc.ServeHTTP(0xbf0178, 0xd34ca0, 0xc000266000, 0xc0001bea00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x125d8a0, 0xd34ca0, 0xc000266000, 0xc0001bea00)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0001a68f0, 0xd34ca0, 0xc000266000, 0xc0001bea00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0001c00a0, 0xd38ca0, 0xc00024e500)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```
which turns out c.AddCloudwatchTimestamp == nil is true. Seemingly input AddCloudwatchTimestamp is a must, there is default value for this is null.

because it is defined as a pointer

```
type cloudwatchData struct {
	ID                     *string
	Metric                 *string
	Service                *string
	Statistics             []string
	Points                 []*cloudwatch.Datapoint
	NilToZero              *bool
	AddCloudwatchTimestamp *bool
	CustomTags             []tag
	Tags                   []tag
	Dimensions             []*cloudwatch.Dimension
}


```
would things be easier if it is a type bool instead of *bool ?

P.S. there is a "hole" in the README doc . The "AddCloudwatchTimestamp" metric atttribute is called "disableTimestamp" in config.yml

@tsupertramp

**Comment by tsupertramp** [comment]
Docs will be updated but can not trigger this issue? - Could you describe it even more? - Is it already fixed maybe? @wutianchen

**Comment by wutianchen** [comment]
@tsupertramp already fixed :) the thing is you can not use config.yml without AddCloudwatchTimestamp attribute. because "yml" library gives AddCloudwatchTimestamp default value null if it is not specified in the config.yml (and this "null" is used somewhere in the code.)

**Comment by tsupertramp** [comment]
Fixed in "your" version or upstream? @wutianchen - If upstream i would close this.

**Comment by thomaspeitz** [comment]
Closing this as no new update.
