### ISSUE TITLE
[panic serving] [ALB] inconsistent label names or help strings for the same fully-qualified name

### ISSUE THREAD

**Issue by karlesnine** [ivx/yet-another-cloudwatch-exporter#76]
#### Hello

Hello Thomas

I've got weird crash error on ALB metric,
This problem is present on version 0.13.3, 0.13.4 and 0.13.6
Please have a look and comment is this a bug or configuration problem:

The probe crash completely and is unable to service any metric

A metric type "up" or "info" for yace would be appreciated to facilitate the creation of alert on the availability of yace himself

#### Error message
```
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: 2019/07/02 08:29:45 http: panic serving 172.21.3.213:36324: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "aws_albtg_request_count_sum", help: "Help is not implemented yet.", constLabels: {dimension_LoadBalancer="app/awseb-AWSEB-B8MZZJGQT11I/cceca96b84631d38",dimension_TargetGroup="targetgroup/awseb-AWSEB-XE5JR40S8X8U/77238dfc7754bac2",name="arn:aws:elasticloadbalancing:eu-west-1:687944316825:targetgroup/awseb-AWSEB-XE5JR40S8X8U/77238dfc7754bac2",tag_Name="vc-pp-pim",tag_Project="pim"}, variableLabels: []}
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: goroutine 23360 [running]:
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: net/http.(*conn).serve.func1(0xc003bd80a0)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:1769 +0x139
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: panic(0xa18bc0, 0xc002f16d20)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/runtime/panic.go:522 +0x1b5
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc001d6e230, 0xc001fb1c48, 0x1, 0x1)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:391 +0xad
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: main.metricsHandler(0xc23fc0, 0xc00027e2a0, 0xc002b10900)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /github/workspace/main.go:51 +0x32f
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: net/http.HandlerFunc.ServeHTTP(0xaf4e58, 0xc23fc0, 0xc00027e2a0, 0xc002b10900)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:1995 +0x44
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: net/http.(*ServeMux).ServeHTTP(0x107a7e0, 0xc23fc0, 0xc00027e2a0, 0xc002b10900)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:2375 +0x1d6
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: net/http.serverHandler.ServeHTTP(0xc00017e750, 0xc23fc0, 0xc00027e2a0, 0xc002b10900)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:2774 +0xa8
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: net/http.(*conn).serve(0xc003bd80a0, 0xc26440, 0xc002bd2840)
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:1878 +0x851
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]: created by net/http.(*Server).Serve
Jul 02 08:29:45 vc-prod-infra-exporter-04 yace_exporter[29797]:         /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

#### Configuration
```
discovery:
  exportedTagsOnMetrics:
    vpn:
      - Project
      - Name
    alb:
      - Project
      - Name
    elb:
      - Project
      - Name
    rds:
      - Project
      - Name
    ec:
     - Project
     - Name
    lambda:
     - Project
     - Name
    kinesis:
     - Project
     - Name
    s3:
     - Project
     - Name
    dynamodb:
     - Project
     - Name
  jobs:
  - region: {{ ec2_region }}
    type: "vpn"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: TunnelState
        statistics:
        - 'Maximum'
        period: 60
        length: 60
        nilToZero: true
      - name: TunnelDataOut
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: TunnelDataIn
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "lambda"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: Throttles
        statistics:
        - 'Average'
        period: 60
        length: 60
        nilToZero: true
      - name: Invocations
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: Errors
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: Duration
        statistics:
        - 'Average'
        period: 60
        length: 60
        nilToZero: true
      - name: Duration
        statistics:
        - 'Minimum'
        period: 60
        length: 60
        nilToZero: true
      - name: Duration
        statistics:
        - 'Maximum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "ec"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: NewConnections
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: GetTypeCmds
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: SetTypeCmds
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: CacheMisses
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: CacheHits
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "rds"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: DatabaseConnections
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: ReadIOPS
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: WriteIOPS
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "alb"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: RequestCount
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HealthyHostCount
        statistics:
        - 'Minimum'
        period: 60
        length: 60
        nilToZero: true
      - name: UnHealthyHostCount
        statistics:
        - 'Maximum'
        period: 60
        length: 60
        nilToZero: true
      - name: Latency
        statistics:
        - 'Average'
        period: 60
        length: 60
        nilToZero: true
      - name: BackendConnectionErrors
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_2XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_5XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_4XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "elb"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: RequestCount
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HealthyHostCount
        statistics:
        - 'Minimum'
        period: 60
        length: 60
        nilToZero: true
      - name: UnHealthyHostCount
        statistics:
        - 'Maximum'
        period: 60
        length: 60
        nilToZero: true
      - name: Latency
        statistics:
        - 'Average'
        period: 60
        length: 60
        nilToZero: true
      - name: BackendConnectionErrors
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_2XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_5XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
      - name: HTTPCode_Backend_4XX
        statistics:
        - 'Sum'
        period: 60
        length: 60
        nilToZero: true
  - region: {{ ec2_region }}
    type: "kinesis"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: PutRecords.Success
        statistics:
        - 'Sum'
        period: 60
        length: 300
      - name: GetRecords.Success
        statistics:
        - 'Sum'
        period: 60
        length: 300    
  - region: eu-west-1
    type: "s3"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    additionalDimensions:
      - name: StorageType
        value: StandardStorage
    metrics:
      - name: NumberOfObjects
        statistics:
          - Average
        period: 86400
        length: 172800
        addCloudwatchTimestamp: true
      - name: BucketSizeBytes
        statistics:
          - Average
        period: 86400
        length: 172800
        addCloudwatchTimestamp: true
  - region: {{ ec2_region }}
    type: "dynamodb"
    searchTags:
      - Key: {{ prometheus_yace_tag_filter }}
        Value: {{ prometheus_yace_tag_value }}
    metrics:
      - name: ReturnedItemCount
        statistics:
        - 'Sum'
        period: 60
        length: 300
```

**Comment by Sushma10037017** [comment]
Hi,
We are also seeing the same error.I am using alb.ingress.kubernetes.io/tags in my ingress which adds tags to both alb and target groups. This tag is being used by prometheus cloudwatch exporter to scrape metrics for alb/tg. However, we are seeing the below error when the tag is present on both alb and targetgroup, removing the tag from target group seems to fix the issue. Any help would be appreciated.

2019/08/27 12:57:09 http: panic serving 10.140.34.245:44316: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "aws_albtg_request_count_sum", help: "Help is not implemented yet.", constLabels: {dimension_LoadBalancer="app/2d6cf76d-ambassadorindevap-6282/xxxxx",dimension_TargetGroup="targetgroup/2d6cf76d-011592e8c5bbb42f660/xxxxxx",name="arn:aws:elasticloadbalancing:ap-south-1:xxxxx:targetgroup/xxxxx"}, variableLabels: []}
goroutine 1685581 [running]:
net/http.(*conn).serve.func1(0xc00051e5a0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x9a5860, 0xc005caf820)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc008d680f0, 0xc001dc9c48, 0x1, 0x1)
	/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:391 +0xad

**Comment by thomaspeitz** [comment]
Thanks for reporting this. I need to recheck the whole alb and target group code and find some better solution.

Will try to spin up a test cluster at the weekend and improve this, so you won't get annoyed by this any more. Sorry for bad ux.
